# Generated by Django 3.1.3 on 2020-11-04 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('redicos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(editable=False)),
                ('texte', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='static/image')),
                ('lien', models.URLField(blank=True)),
                ('preambule', models.TextField(blank=True, verbose_name='preambule')),
                ('date_de_pub', models.DateField(auto_now_add=True, verbose_name='date de publication')),
                ('auteur', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('redico', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='redicos.redico')),
            ],
        ),
    ]
