"""
Django settings for redico3 project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import logging
import os
from pathlib import Path
from django.core.management.utils import get_random_secret_key


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(__file__)) # /home/nimzo/PycharmProjects/redico3
log_file = BASE_DIR+'/logs/redico.log'
print(f"BASE_DIR: {BASE_DIR}")
print(f"log_file: {log_file}")
logging.basicConfig(filename=log_file,level=logging.DEBUG, force=True)

# exit()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_random_secret_key()
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['nimzo.alwaysdata.net', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'six',
    'joueurs',
    'redicos',
    'propositions',
    'evaluations',
    # 'debug_toolbar',
    # 'floppyforms',
    'stats',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',
 ]

ROOT_URLCONF = 'redico3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        # ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                #
                'redicos.context_processors.redicos_importants',
                'redicos.context_processors.joueurs_actifs',
                'redicos.context_processors.redicos_dynamiques',
                'redicos.context_processors.dern_props',
                'redicos.context_processors.dern_evals',
                # 'redicos.context_processors.est_auteur_du_redico',
                # 'redicos.context_procesactizsors.get_redicoId',

            ],
        },
    },
]

WSGI_APPLICATION = 'redico3.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'redico24.db'),
        # 'NAME': BASE_DIR / 'redico24.db',
    }
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'fr-ca'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
# Channels

STATIC_ROOT = os.path.join(BASE_DIR, 'project_static', 'collect')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'css'),
                    )
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#    'django.contrib.staticfiles.finders.DefaultStorageFinder',
)

EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp-nimzo.alwaysdata.net'
EMAIL_HOST_USER = 'nimzo@alwaysdata.net'
EMAIL_HOST_PASSWORD = 'Ponypon1548'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = "nimzo@alwaysdata.net"


logging.info('BASE_DIR:         %s', BASE_DIR)
logging.info('STATIC_ROOT:      %s', STATIC_ROOT)
logging.info('STATIC_URLS:      %s', STATIC_URL)
logging.info('TEMPLATES[DIRS]   %s', TEMPLATES[0]['DIRS'])
logging.info('STATICFILES_DIRS: %s', STATICFILES_DIRS)